version: "3.0"

services:

  db:
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
      - ../dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_DATABASE=grandlyon
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: unless-stopped
    environment:
      - PMA_HOST=db
    ports:
      - "8080:80"

volumes:
  db-data:
